"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { ArrowUpRight, ChevronLeft, ChevronRight, Search, SlidersHorizontal } from "lucide-react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { funnelMetrics } from "@/lib/preview-lockers/conversion";
import { filterPreviews, hasActivity, inQueue, pageOf, type PreviewRow, type Queue, type Referral } from "@/lib/preview-lockers/funnel-workspace";
import { EnrollmentForm, StatusForm } from "./AdminForms";

const panel = "rounded-xl border border-neutral-200 bg-white dark:border-slate-800 dark:bg-[#0c1524]";
const control = "min-h-11 rounded-lg border border-neutral-300 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#ffbb00] dark:border-slate-700 dark:bg-[#101c2e]";
const labels: Record<string, string> = { view: "Preview viewed", photos_view: "Photos viewed", film_view: "Film viewed", claim_click: "Claim button clicked", accepted: "Interest accepted", declined: "Declined", claim_submit: "Claim interest submitted", dashboard_interest: "Dashboard requested", booking_click: "Booking link clicked", booking_confirmed: "Booking confirmed", walkthrough_completed: "Walkthrough completed", referral_created: "Referral link created", referral_copied: "Referral link copied", referral_submit: "Referral intake received", referred_prepared: "Referred preview prepared", referred_claimed: "Referred claim interest", sent: "Invitation marked sent" };
const queues: [Queue, string][] = [["all", "All previews"], ["awaiting", "Awaiting response"], ["dashboard", "Dashboard requests"], ["booked", "Booked calls"], ["declined", "Declines"]];
function date(value: string | null) { return value ? new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "UTC" }) + " UTC" : "Not yet"; }
function responseLabel(row: PreviewRow) { return row.response?.state === "accepted" ? "Claim interest" : row.response?.state === "declined" ? "Declined" : "Awaiting response"; }
function ResponseBadge({ row }: { row: PreviewRow }) {
  return <span className={`inline-flex items-center gap-2 text-xs font-medium ${row.response?.state === "accepted" ? "text-emerald-700 dark:text-emerald-300" : row.response?.state === "declined" ? "text-rose-700 dark:text-rose-300" : "text-neutral-500 dark:text-slate-400"}`}><span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-current" />{responseLabel(row)}</span>;
}
function Pagination({ value, onChange, name }: { value: { page: number; pages: number; total: number }; onChange: (page: number) => void; name: string }) {
  return <nav aria-label={`${name} pagination`} className="flex items-center justify-between gap-3 border-t border-neutral-200 px-4 py-3 dark:border-slate-800"><p className="text-xs text-neutral-500" aria-live="polite">{value.total} results · Page {value.page} of {value.pages}</p><div className="flex gap-2"><button className={`${control} disabled:opacity-40`} disabled={value.page === 1} onClick={() => onChange(value.page - 1)} aria-label={`Previous ${name} page`}><ChevronLeft size={16} /></button><button className={`${control} disabled:opacity-40`} disabled={value.page === value.pages} onClick={() => onChange(value.page + 1)} aria-label={`Next ${name} page`}><ChevronRight size={16} /></button></div></nav>;
}

export function FunnelWorkspace({ rows, referrals, metrics, truncated, contacts, previews, query, listsTruncated }: {
  rows: PreviewRow[]; referrals: Referral[]; metrics: ReturnType<typeof funnelMetrics>; truncated: boolean;
  contacts: { id: string; label: string }[]; previews: { id: string; label: string }[];
  query: Record<string, string | undefined>; listsTruncated: boolean;
}) {
  const opener = useRef<HTMLElement | null>(null);
  const [section, setSection] = useState<"previews" | "referrals">("previews");
  const [queue, setQueue] = useState<Queue>("all");
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("latest");
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<string | null>(null);
  const [selectedReferral, setSelectedReferral] = useState<string | null>(null);
  const [eventPage, setEventPage] = useState(1);
  const filtered = useMemo(() => filterPreviews(rows, search, queue, sort), [rows, search, queue, sort]);
  const previewPage = pageOf(filtered, page);
  const referralPage = pageOf(referrals.filter(r => `${r.full_name} ${r.email} ${r.campaign}`.toLowerCase().includes(search.trim().toLowerCase())), page);
  const current = rows.find(row => row.preview_id === selected);
  const referral = referrals.find(row => row.id === selectedReferral);
  const timeline = pageOf(current?.activity ?? [], eventPage, 15);
  const headline = ["view", "claim_submit", "booking_confirmed", "walkthrough_completed"];
  const openPreview = (id: string) => { opener.current = document.activeElement as HTMLElement; setSelectedReferral(null); setSelected(id); setEventPage(1); };

  return <div className="space-y-6">
    <div className="grid items-start gap-3 lg:grid-cols-[1fr_auto]">
      <details className={panel}><summary className="flex min-h-12 cursor-pointer items-center gap-2 px-4 text-sm font-semibold"><SlidersHorizontal size={16} />Cohort filters<span className="ml-auto text-xs font-normal text-neutral-500">{query.campaign || "All campaigns"}</span></summary><form className="grid gap-3 border-t border-neutral-200 p-4 sm:grid-cols-3 dark:border-slate-800">{["since", "until", "campaign", "channel", "source"].map(key => <label className="text-xs font-medium capitalize" key={key}>{key === "since" ? "Enrolled from" : key === "until" ? "Enrolled through" : key}<input className={`${control} mt-1 w-full`} type={["since", "until"].includes(key) ? "date" : "text"} name={key} defaultValue={query[key]} maxLength={80} /></label>)}<button className={`${control} self-end font-semibold`}>Apply filters</button><p className="text-xs text-neutral-500 sm:col-span-3">UTC enrollment dates define the cohort. Activity is cumulative through now.</p></form></details>
      <EnrollmentForm previews={previews} contacts={contacts} />
    </div>
    {truncated ? <p className="rounded-lg border border-amber-500 p-4 text-sm" role="alert">The safety limit was reached. Totals are withheld and activity may be incomplete. Narrow the cohort filters.</p> : <section className={`${panel} overflow-hidden`} aria-label="Conversion overview">
      <div className="grid grid-cols-2 divide-x divide-neutral-200 border-b border-neutral-200 sm:grid-cols-4 dark:divide-slate-800 dark:border-slate-800">{[["Enrolled previews", metrics.enrolled], ["Invitations sent", metrics.sent], ["Athlete contacts", metrics.athletes], ["Viewing sessions", metrics.sessions]].map(([label, value]) => <div key={label} className="px-5 py-4"><p className="text-xs text-neutral-500 dark:text-slate-400">{label}</p><p className="mt-1 font-mono text-2xl font-semibold">{value}</p></div>)}</div>
      <div className="flex flex-wrap items-end justify-between gap-3 px-5 pt-5"><div><p className="text-xs uppercase tracking-widest text-neutral-500">Sent cohort</p><h2 className="mt-1 text-xl font-semibold">From invitation to conversation</h2></div><span className="text-xs text-neutral-500">{metrics.eventCount} recorded events</span></div>
      <div className="grid grid-cols-2 gap-5 p-5 lg:grid-cols-4">{headline.map((kind, index) => { const stage = metrics.stages.find(s => s.kind === kind)!; const percent = stage.denominator ? Math.round(100 * stage.numerator / stage.denominator) : null; return <article key={kind} className="border-l-2 border-neutral-200 pl-4 dark:border-slate-700"><p className="min-h-10 text-sm text-neutral-600 dark:text-slate-300">{labels[kind]}</p><div className="mt-2 flex items-baseline gap-2"><strong className="font-mono text-3xl tracking-tight">{stage.numerator}</strong><span className="text-sm text-neutral-500">/ {stage.denominator} sent</span></div><div aria-hidden="true" className="my-3 h-2 overflow-hidden rounded-sm bg-neutral-100 dark:bg-slate-800"><div className={index === 1 ? "h-full bg-[#ffbb00]" : "h-full bg-blue-500"} style={{ width: `${percent ?? 0}%` }} /></div><p className="text-xs text-neutral-500">{percent === null ? "No sent denominator" : `${percent}% of sent previews`} · {stage.events} events</p></article>; })}</div>
      <p className="px-5 pb-4 text-xs leading-5 text-neutral-500">Each measure uses the same sent-preview denominator; stages can occur independently. Event counts include all enrolled previews. Claim interest does not verify ownership.</p>
      <details className="border-t border-neutral-200 dark:border-slate-800"><summary className="cursor-pointer px-5 py-3 text-sm font-semibold">All conversion measures · engagement and referrals</summary><div className="overflow-x-auto px-5 pb-4"><table className="w-full min-w-[540px] text-left text-sm"><caption className="py-3 text-left text-xs text-neutral-500">Unique previews and repeat events are separate. Referral stages count referring previews.</caption><thead className="text-xs text-neutral-500"><tr><th className="py-2">Measure</th><th>All unique previews</th><th>Sent cohort</th><th>Events</th></tr></thead><tbody>{metrics.stages.map(s => <tr className="border-t border-neutral-100 dark:border-slate-800" key={s.kind}><th className="py-2 font-normal">{labels[s.kind]}</th><td className="font-mono">{s.previews}</td><td className="font-mono">{s.numerator} / {s.denominator} <span className="text-xs text-neutral-500">{s.denominator ? `(${Math.round(100 * s.numerator / s.denominator)}%)` : "—"}</span></td><td className="font-mono">{s.events}</td></tr>)}</tbody></table></div></details>
    </section>}
    {listsTruncated && <p role="alert" className="text-sm text-amber-700 dark:text-amber-300">A contact, preview, or referral list reached 1,000 rows and may be incomplete.</p>}
    <section className={`${panel} overflow-hidden`} aria-label="Preview operations">
      <div className="flex gap-5 border-b border-neutral-200 px-4 dark:border-slate-800">{([['previews', 'Previews', rows.length], ['referrals', 'Referral preparation', referrals.length]] as const).map(([key, label, count]) => <button key={key} aria-pressed={section === key} onClick={() => { setSection(key); setSearch(""); setPage(1); }} className={`min-h-14 border-b-2 text-sm font-semibold focus-visible:outline focus-visible:outline-[#ffbb00] ${section === key ? "border-[#ffbb00]" : "border-transparent text-neutral-500"}`}>{label}<span className="ml-2 font-mono text-xs text-neutral-500">{count}{truncated ? "+" : ""}</span></button>)}</div>
      {section === "previews" && <div className="flex flex-wrap gap-2 px-4 pt-4" aria-label="Preview queues">{queues.map(([key, label]) => <button key={key} aria-pressed={queue === key} onClick={() => { setQueue(key); setPage(1); }} className={`${control} ${queue === key ? "!border-blue-500 !bg-blue-50 text-blue-800 dark:!bg-blue-950 dark:text-blue-200" : "text-neutral-500"}`}>{label} <span className="ml-1 font-mono text-xs">{rows.filter(r => inQueue(r, key)).length}</span></button>)}</div>}
      <div className="flex flex-wrap gap-3 p-4"><label className="relative min-w-0 flex-1"><span className="sr-only">Search {section === "previews" ? "previews" : "referrals"}</span><Search size={16} className="absolute left-3 top-3.5 text-neutral-400" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search athlete, email or campaign" className={`${control} w-full pl-9`} /></label>{section === "previews" && <label><span className="sr-only">Sort previews</span><select className={control} value={sort} onChange={e => { setSort(e.target.value); setPage(1); }}><option value="latest">Latest activity</option><option value="name">Athlete name</option></select></label>}</div>
      {section === "previews" ? <><div className="hidden grid-cols-[2fr_1fr_1fr_1.5fr_auto] gap-4 bg-neutral-50 px-5 py-2 text-xs text-neutral-500 md:grid dark:bg-slate-900"><span>Athlete / invitation</span><span>Response</span><span>Campaign</span><span>Latest activity</span><span>Details</span></div><ul className="divide-y divide-neutral-100 dark:divide-slate-800">{previewPage.rows.map(row => <li key={row.preview_id}><button onClick={() => openPreview(row.preview_id)} aria-label={`Open timeline for ${row.name}`} className="grid w-full grid-cols-2 items-center gap-3 px-5 py-4 text-left transition-colors hover:bg-neutral-50 focus-visible:outline focus-visible:outline-[#ffbb00] md:grid-cols-[2fr_1fr_1fr_1.5fr_auto] md:gap-4 dark:hover:bg-slate-900"><span className="min-w-0"><span className="block truncate text-sm font-semibold">{row.name}</span><span className="mt-1 block text-xs text-neutral-500">{row.sent_at ? `Sent ${date(row.sent_at)}` : "Invitation not marked sent"}</span></span><ResponseBadge row={row} /><span className="truncate text-xs text-neutral-500">{row.campaign}</span><span className="text-xs"><span className="block">{row.activity[0] ? labels[row.activity[0].kind] : "No activity yet"}</span><span className="mt-1 block text-neutral-500">{date(row.activity[0]?.created_at ?? null)}</span></span><ArrowUpRight className="hidden text-neutral-400 md:block" size={16} /></button></li>)}</ul>{!previewPage.total && <div className="p-10 text-center"><h3 className="font-semibold">No previews match this view</h3><p className="mt-2 text-sm text-neutral-500">Try another queue or search, adjust the cohort, or enroll an existing preview.</p></div>}<Pagination value={previewPage} onChange={setPage} name="previews" /></> : <><p className="px-5 pb-3 text-xs text-neutral-500">Self-submitted referrals. Duplicate and self-referral attempts do not create acquisition records.</p><ul className="divide-y divide-neutral-100 dark:divide-slate-800">{referralPage.rows.map(row => <li key={row.id}><button onClick={() => { opener.current = document.activeElement as HTMLElement; setSelected(null); setSelectedReferral(row.id); }} className="flex min-h-20 w-full items-center justify-between gap-3 px-5 py-4 text-left hover:bg-neutral-50 focus-visible:outline focus-visible:outline-[#ffbb00] dark:hover:bg-slate-900"><span className="min-w-0"><strong className="block text-sm">{row.full_name}</strong><span className="block truncate text-xs text-neutral-500">{row.email}</span></span><span className="text-xs">{row.preview_id ? "Preview prepared" : row.contact_id ? "Ready to prepare" : "Match needs review"}</span><ArrowUpRight size={16} /></button></li>)}</ul>{!referralPage.total && <p className="p-10 text-center text-sm text-neutral-500">No referred athletes match this view.</p>}<Pagination value={referralPage} onChange={setPage} name="referrals" /></>}
    </section>
    <Sheet open={Boolean(current || referral)} onOpenChange={open => { if (!open) { setSelected(null); setSelectedReferral(null); } }}><SheetContent onCloseAutoFocus={event => { event.preventDefault(); opener.current?.focus(); }} className="w-full overflow-y-auto bg-white p-6 sm:max-w-xl dark:bg-[#0c1524]">
      <SheetHeader className="p-0 pr-7"><SheetTitle className="text-2xl">{current?.name ?? referral?.full_name}</SheetTitle><SheetDescription>{current ? "Preview response and timeline" : "Referral preparation"}</SheetDescription></SheetHeader>
      {current && <><div className="flex items-center justify-between"><ResponseBadge row={current} /><span className="text-xs text-neutral-500">{current.campaign}</span></div><div className="flex flex-wrap gap-2"><Link className={control + " inline-flex items-center"} href={`/admin/gtm/contacts?contact=${current.contact_id}`}>GTM contact</Link><Link className={control + " inline-flex items-center"} href={`/admin/preview-lockers/${current.preview_id}/edit`}>Manage preview</Link>{current.slug && <Link className={control + " inline-flex items-center"} href={`/preview-lockers/${current.slug}`}>Open preview</Link>}</div><p className="text-xs text-neutral-500">{current.channel} · {current.source} · {current.relationship} relationship</p>
        {current.response && <section className="rounded-lg bg-neutral-50 p-4 text-sm dark:bg-slate-900"><h3 className="font-semibold">Athlete response</h3><p className="mt-2 break-all">{current.response.email || "No email supplied"}</p><p className="mt-2 text-xs text-neutral-500">Updates permission: {current.response.updates_permission ? "Yes" : "No"} · Dashboard: {current.response.dashboard_interest ? "Requested" : "Not requested"}</p>{current.response.state === "declined" && <p className="mt-3">{current.response.decline_reason || "No reason supplied"}</p>}</section>}
        <div className="space-y-3">{!current.sent_at && <StatusForm key={`${current.preview_id}-sent`} preview={current.preview_id} action="sent" label="Mark invitation sent" />}{current.response?.state === "accepted" && <>{!hasActivity(current, "booking_confirmed") && <StatusForm key={`${current.preview_id}-booking`} preview={current.preview_id} action="booking_confirmed" label="Confirm booking occurred" />}{!hasActivity(current, "walkthrough_completed") && <StatusForm key={`${current.preview_id}-walkthrough`} preview={current.preview_id} action="walkthrough_completed" label="Record completed walkthrough" />}</>}</div>
        <section><div className="mb-5 flex items-center justify-between"><h3 className="font-semibold">Activity timeline</h3><span className="text-xs text-neutral-500">{current.activity.length} events · newest first</span></div>{truncated && <p role="alert" className="mb-3 text-sm text-amber-700">This timeline may be incomplete. Narrow the cohort.</p>}<ol className="ml-2 border-l border-neutral-200 dark:border-slate-700">{timeline.rows.map(event => <li className="relative pb-6 pl-5" key={event.id}><span aria-hidden="true" className="absolute -left-1 top-1.5 h-2 w-2 rounded-full bg-blue-500" /><p className="text-sm font-medium">{labels[event.kind]}</p><time className="mt-1 block font-mono text-[11px] text-neutral-500" dateTime={event.created_at}>{date(event.created_at)}</time></li>)}</ol>{!timeline.total && <p className="py-5 text-sm text-neutral-500">No activity recorded yet.</p>}{timeline.pages > 1 && <Pagination value={timeline} onChange={setEventPage} name="timeline" />}</section></>}
      {referral && <div className="space-y-5"><p className="break-all text-sm">{referral.email}</p><p className="text-sm text-neutral-500">Referred by {rows.find(r => r.preview_id === referral.referrer_preview_id)?.name ?? "athlete"} · {referral.campaign} / {referral.source}</p>{referral.contact_id ? <div className="flex flex-wrap gap-2"><Link className={control + " inline-flex items-center"} href={`/admin/gtm/contacts?contact=${referral.contact_id}`}>GTM contact</Link><Link className={control + " inline-flex items-center"} href={referral.preview_id ? `/admin/preview-lockers/${referral.preview_id}/edit` : `/admin/preview-lockers/new?intake=${referral.id}`}>{referral.preview_id ? "Edit prepared preview" : "Prepare private preview"}</Link></div> : <><p className="text-sm">Ambiguous email matches. Review the contact before linking this referral.</p><StatusForm key={referral.id} preview={referral.referrer_preview_id} referral={referral.id} contacts={contacts} action="resolve_referral" label="Link reviewed contact" /></>}<details className="text-xs text-neutral-500"><summary className="cursor-pointer">Preparation reference</summary><p className="mt-2 break-all">Reserved preview ID: {referral.reserved_preview_id}</p></details></div>}
    </SheetContent></Sheet>
  </div>;
}
