import Link from "next/link";
import { GtmNavigation } from "@/components/admin/gtm/GtmNavigation";
import { previewAdmin } from "@/lib/preview-lockers/server";
import { attributionCode, funnelMetrics } from "@/lib/preview-lockers/conversion";
import { EnrollmentForm, StatusForm } from "./AdminForms";
export const dynamic="force-dynamic";
export default async function Funnel({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const {client}=await previewAdmin(); const query=await searchParams;
  let cohort=client.from("preview_conversion_campaigns").select("*").eq("is_test",false).order("created_at",{ascending:false}).limit(1000);
  for(const key of ["campaign","channel","source"]){if(query[key]&&attributionCode.safeParse(query[key]).success)cohort=cohort.eq(key,query[key]);}
  for(const [key,op] of [["since","gte"],["until","lte"]] as const){if(query[key]&&/^\d{4}-\d{2}-\d{2}$/.test(query[key]!))cohort=cohort[op]("created_at",`${query[key]}T${key==="since"?"00:00:00":"23:59:59.999"}Z`);}
  const [campaigns,previews,contacts,referrals]=await Promise.all([cohort,client.from("preview_lockers").select("id,full_name,slug").limit(1000),client.from("gtm_contacts").select("id,display_name,email,player_master_gsis_id").eq("archived",false).limit(1000),client.from("preview_conversion_referrals").select("*").order("created_at",{ascending:false}).limit(1000)]);
  if([campaigns,previews,contacts,referrals].some(r=>r.error))throw new Error("Preview funnel data unavailable");
  const rows=campaigns.data??[]; const ids=rows.map(r=>r.preview_id);
  const [events,responses]=ids.length?await Promise.all([client.from("preview_conversion_events").select("*").in("preview_id",ids).order("created_at",{ascending:false}).limit(1000),client.from("preview_conversion_responses").select("*").in("preview_id",ids).limit(1000)]):[{data:[],error:null},{data:[],error:null}];
  if(events.error||responses.error)throw new Error("Conversion activity unavailable");
  const activity=events.data??[]; const replies=responses.data??[];
  const truncated=rows.length>=1000||activity.length>=1000||replies.length>=1000;
  const metrics=funnelMetrics(rows,activity);
  const contactOptions=(contacts.data??[]).map(c=>({id:c.id,label:c.display_name||c.player_master_gsis_id||c.id}));
  const lookup=(id:string)=>(previews.data??[]).find(p=>p.id===id);
  const display=(id:string)=>lookup(id)?.full_name||id;
  const filteredReferrals=(referrals.data??[]).filter(r=>ids.includes(r.referrer_preview_id));
  const has=(id:string,kind:string)=>activity.some(e=>e.preview_id===id&&e.kind===kind);
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><GtmNavigation/><h1 className="text-3xl font-semibold">Preview conversion funnel</h1>
    <p>90-day experiment · athlete interest is not verified ownership. “Viewed” means an authorized visible-page visit, never an email open. Admin/test activity is excluded.</p>
    <form className="flex flex-wrap items-end gap-3">{["since","until","campaign","channel","source"].map(key=><label key={key}>{key}<input className="block min-h-11 max-w-44 rounded border bg-transparent p-2" type={["since","until"].includes(key)?"date":"text"} name={key} defaultValue={query[key]} maxLength={80}/></label>)}<button className="min-h-11 rounded border px-4">Apply filters</button></form>
    <p>UTC enrollment-date cohort; activity is cumulative through now. Every stage shows unique sent previews / sent previews. Event counts and referral intake counts are separate.</p>
    {truncated?<p role="alert">Results reached the 1,000-row limit. Totals are withheld. Narrow the cohort; listed activity may be incomplete.</p>:<><p>{metrics.enrolled} enrolled previews · {metrics.athletes} distinct GTM athlete contacts · {metrics.sent} sent · {metrics.sessions} viewing sessions · {metrics.eventCount} events</p><div className="overflow-x-auto"><table className="w-full text-left"><caption>Conversion numerators and denominators</caption><thead><tr><th>Stage</th><th>All unique previews</th><th>Sent cohort conversion</th><th>Events</th></tr></thead><tbody>{metrics.stages.map(s=><tr className="border-t" key={s.kind}><th className="p-2 text-left font-normal">{s.kind.replaceAll("_"," ")}</th><td>{s.previews}</td><td>{s.numerator}/{s.denominator} {s.denominator?`(${Math.round(100*s.numerator/s.denominator)}%)`:"— no sent denominator"}</td><td>{s.events}</td></tr>)}</tbody></table></div></>}
    {[previews,contacts,referrals].some(r=>(r.data?.length??0)>=1000)&&<p role="alert">A preparation/contact list reached 1,000 rows; it may be incomplete.</p>}
    <EnrollmentForm previews={(previews.data??[]).map(p=>({id:p.id,label:p.full_name}))} contacts={contactOptions}/>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Preview response and timeline</h2>{!rows.length&&<p>No enrolled previews match this cohort.</p>}{rows.map(c=>{const response=replies.find(r=>r.preview_id===c.preview_id);return <details className="rounded border p-4" key={c.preview_id}><summary>{display(c.preview_id)} · {response?.state??"Awaiting athlete response"} · {c.sent_at?"Sent":"Not marked sent"}</summary><div className="mt-3 space-y-3"><p>{c.campaign} · {c.source} · {c.channel} · {c.relationship}</p><p className="break-all">Preview ID: {c.preview_id}</p><Link className="underline" href={`/admin/gtm/contacts?contact=${c.contact_id}`}>GTM contact · notes and discovery</Link><p><Link className="underline" href={`/admin/preview-lockers/${c.preview_id}/edit`}>Edit preview / assign or revoke viewer / Admin completion</Link></p>{lookup(c.preview_id)&&<Link className="underline" href={`/preview-lockers/${lookup(c.preview_id)!.slug}`}>Private preview</Link>}
      {!c.sent_at&&<StatusForm preview={c.preview_id} action="sent" label="Mark invitation sent"/>}
      {response&&<p>{response.email} · Updates permission: {response.updates_permission?"Yes":"No"} · Dashboard: {response.dashboard_interest?"Requested":"Not requested"}{response.decline_reason&&` · Reason: ${response.decline_reason}`}</p>}
      {response?.state==="accepted"&&<div className="flex flex-wrap gap-3">{!has(c.preview_id,"booking_confirmed")&&<StatusForm preview={c.preview_id} action="booking_confirmed" label="Confirm booking occurred"/>}{!has(c.preview_id,"walkthrough_completed")&&<StatusForm preview={c.preview_id} action="walkthrough_completed" label="Record completed walkthrough"/>}</div>}
      <ol>{activity.filter(e=>e.preview_id===c.preview_id).map(e=><li key={e.id}>{e.created_at} · {e.kind.replaceAll("_"," ")}</li>)}</ol></div></details>;})}</section>
    {[{title:"Dashboard requests",rows:replies.filter(r=>r.dashboard_interest&&!has(r.preview_id,"walkthrough_completed"))},{title:"Booked calls",rows:replies.filter(r=>has(r.preview_id,"booking_confirmed")&&!has(r.preview_id,"walkthrough_completed"))},{title:"Declines",rows:replies.filter(r=>r.state==="declined")}].map(q=><section key={q.title}><h2 className="text-xl font-semibold">{q.title}</h2>{q.rows.length?<ul>{q.rows.map(r=><li key={r.preview_id}>{display(r.preview_id)} · {r.email||r.decline_reason||"No reason supplied"}</li>)}</ul>:<p>No matching responses in the loaded cohort.</p>}</section>)}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Referred athletes · preparation queue</h2><p>{filteredReferrals.length} self-intakes in the loaded cohort. Duplicate and self-referral attempts do not create acquisition records.</p>{filteredReferrals.map(r=><div className="rounded border p-4" key={r.id}><p>{r.full_name} · {r.email}</p><p>From {display(r.referrer_preview_id)} · {r.campaign}/{r.source}</p><p className="break-all">Reserved preview ID: {r.reserved_preview_id}</p>{r.contact_id?<><Link className="underline" href={`/admin/gtm/contacts?contact=${r.contact_id}`}>GTM contact</Link><p><Link className="underline" href={r.preview_id?`/admin/preview-lockers/${r.preview_id}/edit`:`/admin/preview-lockers/new?intake=${r.id}`}>{r.preview_id?"Edit prepared preview":"Prepare private preview"}</Link></p></>:<><p>Ambiguous email matches. Review in GTM before explicitly linking the intake.</p><StatusForm preview={r.referrer_preview_id} referral={r.id} contacts={contactOptions} action="resolve_referral" label="Link reviewed contact"/></>}</div>)}</section>
  </main>;
}
