// GENERATED by scripts/generate-intelligence-workflow-types.mjs from isolated PostgreSQL catalog.
// Explicit development/production scope types; not a deployed schema attestation.
export type WorkflowJson = string | number | boolean | null | { [key: string]: WorkflowJson | undefined } | WorkflowJson[];

export interface IntelligenceWorkflowTables {
  intelligence_review_opportunities: {
    Row: {
      id: string;
      environment: string;
      opportunity_key: string;
      player_id: string;
      moment_id: string | null;
      run_id: string | null;
      rule_version: string;
      signal_keys: string[];
      evidence_ids: string[];
      input_snapshot: WorkflowJson;
      title: string;
      explanation: string;
      state: string;
      readiness_blockers: string[];
      assignee_id: string | null;
      expires_at: string | null;
      revision: number;
      created_by: string;
      updated_by: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      environment?: string;
      opportunity_key: string;
      player_id: string;
      moment_id?: string | null;
      run_id?: string | null;
      rule_version: string;
      signal_keys: string[];
      evidence_ids?: string[];
      input_snapshot: WorkflowJson;
      title: string;
      explanation: string;
      state?: string;
      readiness_blockers?: string[];
      assignee_id?: string | null;
      expires_at?: string | null;
      revision?: number;
      created_by: string;
      updated_by: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      environment?: string;
      opportunity_key?: string;
      player_id?: string;
      moment_id?: string | null;
      run_id?: string | null;
      rule_version?: string;
      signal_keys?: string[];
      evidence_ids?: string[];
      input_snapshot?: WorkflowJson;
      title?: string;
      explanation?: string;
      state?: string;
      readiness_blockers?: string[];
      assignee_id?: string | null;
      expires_at?: string | null;
      revision?: number;
      created_by?: string;
      updated_by?: string;
      created_at?: string;
      updated_at?: string;
    };
  };
  intelligence_moment_asset_links: {
    Row: {
      id: string;
      environment: string;
      player_id: string;
      moment_id: string;
      legacy_media_id: string | null;
      legacy_video_id: string | null;
      status: string;
      evidence_ids: string[];
      review_reason: string;
      reviewed_by: string;
      revision: number;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      environment?: string;
      player_id: string;
      moment_id: string;
      legacy_media_id?: string | null;
      legacy_video_id?: string | null;
      status: string;
      evidence_ids: string[];
      review_reason: string;
      reviewed_by: string;
      revision?: number;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      environment?: string;
      player_id?: string;
      moment_id?: string;
      legacy_media_id?: string | null;
      legacy_video_id?: string | null;
      status?: string;
      evidence_ids?: string[];
      review_reason?: string;
      reviewed_by?: string;
      revision?: number;
      created_at?: string;
      updated_at?: string;
    };
  };
  intelligence_activation_drafts: {
    Row: {
      id: string;
      opportunity_id: string;
      title: string;
      description: string;
      proposed_brands: WorkflowJson;
      intended_use: string;
      release_at: string | null;
      state: string;
      owner_id: string;
      revision: number;
      review_approved_revision: number | null;
      metrics: WorkflowJson | null;
      created_by: string;
      updated_by: string;
      created_at: string;
      updated_at: string;
      environment: string;
    };
    Insert: {
      id?: string;
      opportunity_id: string;
      title: string;
      description: string;
      proposed_brands?: WorkflowJson;
      intended_use: string;
      release_at?: string | null;
      state?: string;
      owner_id: string;
      revision?: number;
      review_approved_revision?: number | null;
      metrics?: WorkflowJson | null;
      created_by: string;
      updated_by: string;
      created_at?: string;
      updated_at?: string;
      environment?: string;
    };
    Update: {
      id?: string;
      opportunity_id?: string;
      title?: string;
      description?: string;
      proposed_brands?: WorkflowJson;
      intended_use?: string;
      release_at?: string | null;
      state?: string;
      owner_id?: string;
      revision?: number;
      review_approved_revision?: number | null;
      metrics?: WorkflowJson | null;
      created_by?: string;
      updated_by?: string;
      created_at?: string;
      updated_at?: string;
      environment?: string;
    };
  };
  intelligence_activation_assets: {
    Row: {
      id: string;
      activation_id: string;
      moment_asset_link_id: string;
      active: boolean;
      created_at: string;
      updated_at: string;
      environment: string;
    };
    Insert: {
      id?: string;
      activation_id: string;
      moment_asset_link_id: string;
      active?: boolean;
      created_at?: string;
      updated_at?: string;
      environment?: string;
    };
    Update: {
      id?: string;
      activation_id?: string;
      moment_asset_link_id?: string;
      active?: boolean;
      created_at?: string;
      updated_at?: string;
      environment?: string;
    };
  };
  intelligence_workflow_history: {
    Row: {
      id: string;
      opportunity_id: string | null;
      activation_id: string | null;
      moment_asset_link_id: string | null;
      command_id: string;
      actor_id: string;
      action: string;
      reason: string;
      revision: number;
      request_hash: string;
      before_snapshot: WorkflowJson | null;
      after_snapshot: WorkflowJson;
      created_at: string;
      environment: string;
    };
    Insert: {
      id?: string;
      opportunity_id?: string | null;
      activation_id?: string | null;
      moment_asset_link_id?: string | null;
      command_id: string;
      actor_id: string;
      action: string;
      reason: string;
      revision: number;
      request_hash: string;
      before_snapshot?: WorkflowJson | null;
      after_snapshot: WorkflowJson;
      created_at?: string;
      environment?: string;
    };
    Update: {
      id?: string;
      opportunity_id?: string | null;
      activation_id?: string | null;
      moment_asset_link_id?: string | null;
      command_id?: string;
      actor_id?: string;
      action?: string;
      reason?: string;
      revision?: number;
      request_hash?: string;
      before_snapshot?: WorkflowJson | null;
      after_snapshot?: WorkflowJson;
      created_at?: string;
      environment?: string;
    };
  };
}

export interface IntelligenceWorkflowFunctions {
  mutate_intelligence_workflow: {
    Args: {
      p_actor_id: string;
      p_command: WorkflowJson;
    };
    Returns: WorkflowJson;
  };
  mutate_intelligence_workflow_in_environment: {
    Args: {
      p_actor_id: string;
      p_command: WorkflowJson;
      p_environment: string;
    };
    Returns: WorkflowJson;
  };
  read_intelligence_workflows: {
    Args: {
      p_player_id: string;
    };
    Returns: WorkflowJson;
  };
  read_intelligence_workflows_in_environment: {
    Args: {
      p_player_id: string;
      p_environment: string;
    };
    Returns: WorkflowJson;
  };
}
