// GENERATED by node scripts/generate-intelligence-types.mjs from an isolated PostgreSQL catalog.
// Additive local migration schema only; not a deployed database attestation.
export type IntelligenceJson = string | number | boolean | null | { [key: string]: IntelligenceJson | undefined } | IntelligenceJson[];

export interface IntelligenceTables {
  intelligence_sources: {
    Row: {
      id: string;
      source_key: string;
      name: string;
      provider: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      source_key: string;
      name: string;
      provider: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      source_key?: string;
      name?: string;
      provider?: string;
      created_at?: string;
      updated_at?: string;
    };
  };
  intelligence_ingestions: {
    Row: {
      id: string;
      source_id: string;
      namespace: string;
      external_id: string | null;
      locator: string | null;
      fetched_at: string;
      normalizer_version: string;
      idempotency_key: string;
      raw_payload: IntelligenceJson;
      normalized_candidate: IntelligenceJson;
      normalization_status: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      source_id: string;
      namespace: string;
      external_id?: string | null;
      locator?: string | null;
      fetched_at: string;
      normalizer_version: string;
      idempotency_key: string;
      raw_payload: IntelligenceJson;
      normalized_candidate?: IntelligenceJson;
      normalization_status?: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      source_id?: string;
      namespace?: string;
      external_id?: string | null;
      locator?: string | null;
      fetched_at?: string;
      normalizer_version?: string;
      idempotency_key?: string;
      raw_payload?: IntelligenceJson;
      normalized_candidate?: IntelligenceJson;
      normalization_status?: string;
      created_at?: string;
      updated_at?: string;
    };
  };
  moments: {
    Row: {
      id: string;
      title: string;
      occurred_on: string | null;
      occurred_year: number | null;
      date_precision: string;
      sport: string | null;
      event_id: string | null;
      status: string;
      confidence: number | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      title: string;
      occurred_on?: string | null;
      occurred_year?: number | null;
      date_precision?: string;
      sport?: string | null;
      event_id?: string | null;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      title?: string;
      occurred_on?: string | null;
      occurred_year?: number | null;
      date_precision?: string;
      sport?: string | null;
      event_id?: string | null;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  moment_athletes: {
    Row: {
      id: string;
      moment_id: string;
      player_id: string;
      relationship_type: string;
      status: string;
      confidence: number | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      moment_id: string;
      player_id: string;
      relationship_type: string;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      moment_id?: string;
      player_id?: string;
      relationship_type?: string;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
  };
  intelligence_evidence: {
    Row: {
      id: string;
      player_id: string;
      moment_id: string | null;
      source_id: string;
      ingestion_id: string | null;
      fact_type: string;
      statement: string;
      structured_data: IntelligenceJson;
      status: string;
      confidence: number | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      player_id: string;
      moment_id?: string | null;
      source_id: string;
      ingestion_id?: string | null;
      fact_type: string;
      statement: string;
      structured_data?: IntelligenceJson;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      player_id?: string;
      moment_id?: string | null;
      source_id?: string;
      ingestion_id?: string | null;
      fact_type?: string;
      statement?: string;
      structured_data?: IntelligenceJson;
      status?: string;
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
  };
}

export interface IntelligenceFunctions {
  review_intelligence_observation: {
    Args: {
      p_packet: IntelligenceJson;
      p_actor_id: string;
    };
    Returns: IntelligenceJson;
  };
}
