// Generated by Supabase CLI from the isolated full release schema plus conversion migration.
import type {Json} from './database.generated';
export type ConversionDatabase={public:{Tables: {
preview_conversion_campaigns: {
        Row: {
          campaign: string
          channel: string
          contact_id: string
          created_at: string
          created_by: string
          is_test: boolean
          preview_id: string
          referral_token: string | null
          relationship: string
          sent_at: string | null
          source: string
          updated_at: string
        }
        Insert: {
          campaign: string
          channel: string
          contact_id: string
          created_at?: string
          created_by: string
          is_test?: boolean
          preview_id: string
          referral_token?: string | null
          relationship: string
          sent_at?: string | null
          source: string
          updated_at?: string
        }
        Update: {
          campaign?: string
          channel?: string
          contact_id?: string
          created_at?: string
          created_by?: string
          is_test?: boolean
          preview_id?: string
          referral_token?: string | null
          relationship?: string
          sent_at?: string | null
          source?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "preview_conversion_campaigns_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: true
            referencedRelation: "gtm_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "preview_conversion_campaigns_preview_id_fkey"
            columns: ["preview_id"]
            isOneToOne: true
            referencedRelation: "preview_lockers"
            referencedColumns: ["id"]
          },
        ]
      }
preview_conversion_events: {
        Row: {
          actor_id: string | null
          created_at: string
          id: string
          kind: string
          preview_id: string
          related_id: string | null
          request_id: string
          session_id: string
          utm: Json
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: string
          kind: string
          preview_id: string
          related_id?: string | null
          request_id: string
          session_id: string
          utm?: Json
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: string
          kind?: string
          preview_id?: string
          related_id?: string | null
          request_id?: string
          session_id?: string
          utm?: Json
        }
        Relationships: [
          {
            foreignKeyName: "conversion_event_related_referral"
            columns: ["related_id"]
            isOneToOne: false
            referencedRelation: "preview_conversion_referrals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "preview_conversion_events_preview_id_fkey"
            columns: ["preview_id"]
            isOneToOne: false
            referencedRelation: "preview_conversion_campaigns"
            referencedColumns: ["preview_id"]
          },
        ]
      }
preview_conversion_referrals: {
        Row: {
          actor_id: string
          campaign: string
          consent_at: string
          contact_id: string | null
          created_at: string
          email: string
          full_name: string
          id: string
          preview_id: string | null
          referrer_preview_id: string
          reserved_preview_id: string
          source: string
        }
        Insert: {
          actor_id: string
          campaign: string
          consent_at?: string
          contact_id?: string | null
          created_at?: string
          email: string
          full_name: string
          id?: string
          preview_id?: string | null
          referrer_preview_id: string
          reserved_preview_id?: string
          source: string
        }
        Update: {
          actor_id?: string
          campaign?: string
          consent_at?: string
          contact_id?: string | null
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          preview_id?: string | null
          referrer_preview_id?: string
          reserved_preview_id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "preview_conversion_referrals_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "gtm_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "preview_conversion_referrals_preview_id_fkey"
            columns: ["preview_id"]
            isOneToOne: true
            referencedRelation: "preview_lockers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "preview_conversion_referrals_referrer_preview_id_fkey"
            columns: ["referrer_preview_id"]
            isOneToOne: false
            referencedRelation: "preview_conversion_campaigns"
            referencedColumns: ["preview_id"]
          },
        ]
      }
preview_conversion_responses: {
        Row: {
          actor_id: string
          created_at: string
          dashboard_interest: boolean
          decline_reason: string | null
          email: string | null
          preview_id: string
          state: string
          updated_at: string
          updates_permission: boolean
        }
        Insert: {
          actor_id: string
          created_at?: string
          dashboard_interest?: boolean
          decline_reason?: string | null
          email?: string | null
          preview_id: string
          state: string
          updated_at?: string
          updates_permission?: boolean
        }
        Update: {
          actor_id?: string
          created_at?: string
          dashboard_interest?: boolean
          decline_reason?: string | null
          email?: string | null
          preview_id?: string
          state?: string
          updated_at?: string
          updates_permission?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "preview_conversion_responses_preview_id_fkey"
            columns: ["preview_id"]
            isOneToOne: true
            referencedRelation: "preview_conversion_campaigns"
            referencedColumns: ["preview_id"]
          },
        ]
      }
}
Views: Record<string,never>
Functions: {
preview_conversion: {
        Args: {
          p_action: string
          p_data: Json
          p_preview: string
          p_request: string
          p_session: string
        }
        Returns: Json
      }
}
Enums:Record<string,never>;CompositeTypes:Record<string,never>}};
