// GENERATED by scripts/generate-preview-delivery-types.mjs from downloaded staging catalog.
// Scoped snapshot: three tables and ten public RPCs; not a full database schema.
// Staging yevihzsgqagvuulymqum; system 7666007964130682852; captured 2026-10-09T20:05:26.685956+00:00.
// Source JSON SHA-256: f8b48d7f374999f33e763cee32811cca97c7a56d69937edce0b1c2864e649fae
import type { Json } from "./database.generated";

export type PreviewDeliveryDatabase = { public: { Tables: {
  analytics_delivery_batches: {
    Row: {
      id: string;
      environment: string;
      state: string;
      event_count: number;
      byte_count: number;
      publish_attempts: number;
      worker_attempts: number;
      publish_lease_token: string | null;
      publish_lease_until: string | null;
      worker_lease_token: string | null;
      worker_lease_until: string | null;
      next_attempt_at: string;
      message_id: string | null;
      last_error_code: string | null;
      created_at: string;
      updated_at: string;
      acknowledged_at: string | null;
    };
    Insert: {
      id?: string;
      environment: string;
      state?: string;
      event_count: number;
      byte_count: number;
      publish_attempts?: number;
      worker_attempts?: number;
      publish_lease_token?: string | null;
      publish_lease_until?: string | null;
      worker_lease_token?: string | null;
      worker_lease_until?: string | null;
      next_attempt_at?: string;
      message_id?: string | null;
      last_error_code?: string | null;
      created_at?: string;
      updated_at?: string;
      acknowledged_at?: string | null;
    };
    Update: {
      id?: string;
      environment?: string;
      state?: string;
      event_count?: number;
      byte_count?: number;
      publish_attempts?: number;
      worker_attempts?: number;
      publish_lease_token?: string | null;
      publish_lease_until?: string | null;
      worker_lease_token?: string | null;
      worker_lease_until?: string | null;
      next_attempt_at?: string;
      message_id?: string | null;
      last_error_code?: string | null;
      created_at?: string;
      updated_at?: string;
      acknowledged_at?: string | null;
    };
    Relationships: [];
  };
  analytics_delivery_outbox: {
    Row: {
      environment: string;
      event_id: string;
      analytics_event_id: string;
      envelope: Json;
      payload_hash: string;
      batch_id: string | null;
      accepted_at: string;
    };
    Insert: {
      environment: string;
      event_id: string;
      analytics_event_id: string;
      envelope: Json;
      payload_hash: string;
      batch_id?: string | null;
      accepted_at?: string;
    };
    Update: {
      environment?: string;
      event_id?: string;
      analytics_event_id?: string;
      envelope?: Json;
      payload_hash?: string;
      batch_id?: string | null;
      accepted_at?: string;
    };
    Relationships: [
      {
        "foreignKeyName": "analytics_delivery_outbox_analytics_event_id_fkey",
        "columns": [
          "analytics_event_id"
        ],
        "isOneToOne": true,
        "referencedRelation": "analytics_events",
        "referencedColumns": [
          "id"
        ]
      },
      {
        "foreignKeyName": "analytics_delivery_outbox_batch_id_fkey",
        "columns": [
          "batch_id"
        ],
        "isOneToOne": false,
        "referencedRelation": "analytics_delivery_batches",
        "referencedColumns": [
          "id"
        ]
      },
      {
        "foreignKeyName": "analytics_delivery_outbox_environment_batch",
        "columns": [
          "batch_id",
          "environment"
        ],
        "isOneToOne": false,
        "referencedRelation": "analytics_delivery_batches",
        "referencedColumns": [
          "id",
          "environment"
        ]
      }
    ];
  };
  preview_link_inquiries: {
    Row: {
      id: string;
      preview_id: string;
      email: string;
      feature_requests: string | null;
      consent_at: string;
      created_at: string;
      analytics_session_id: string | null;
      analytics_environment: string | null;
    };
    Insert: {
      id?: string;
      preview_id: string;
      email: string;
      feature_requests?: string | null;
      consent_at?: string;
      created_at?: string;
      analytics_session_id?: string | null;
      analytics_environment?: string | null;
    };
    Update: {
      id?: string;
      preview_id?: string;
      email?: string;
      feature_requests?: string | null;
      consent_at?: string;
      created_at?: string;
      analytics_session_id?: string | null;
      analytics_environment?: string | null;
    };
    Relationships: [
      {
        "foreignKeyName": "preview_link_inquiries_preview_id_fkey",
        "columns": [
          "preview_id"
        ],
        "isOneToOne": false,
        "referencedRelation": "preview_lockers",
        "referencedColumns": [
          "id"
        ]
      }
    ];
  };
}; Views: Record<string, never>; Functions: {
  accept_analytics_delivery_event: { Args: {
    p_event: Json;
    p_envelope: Json;
  }; Returns: Json };
  acquire_analytics_delivery_batch: { Args: {
    p_batch_id: string;
    p_environment: string;
    p_lease_token: string;
    p_lease_seconds?: number;
  }; Returns: Json };
  configure_preview_analytics_capture: { Args: {
    p_environment: string;
  }; Returns: undefined };
  get_analytics_delivery_batch: { Args: {
    p_batch_id: string;
    p_environment: string;
  }; Returns: Json };
  lease_analytics_delivery_batch: { Args: {
    p_environment: string;
    p_limit: number;
    p_byte_cap: number;
    p_lease_token: string;
    p_lease_seconds?: number;
  }; Returns: Json };
  mark_analytics_delivery_published: { Args: {
    p_batch_id: string;
    p_lease_token: string;
    p_message_id: string;
  }; Returns: boolean };
  record_preview_analytics_event: { Args: {
    p_input: Json;
    p_actor: string;
    p_environment: string;
  }; Returns: Json };
  release_analytics_delivery_publish: { Args: {
    p_batch_id: string;
    p_lease_token: string;
    p_error_code: string;
  }; Returns: boolean };
  save_preview_link_inquiry: { Args: {
    p_preview: string;
    p_email: string;
    p_features: string;
    p_session: string;
    p_actor: string;
    p_environment: string;
  }; Returns: Json };
  settle_analytics_delivery_batch: { Args: {
    p_batch_id: string;
    p_lease_token: string;
    p_outcome: string;
    p_error_code?: string;
  }; Returns: boolean };
}; Enums: Record<string, never>; CompositeTypes: Record<string, never> } };
