import type { BetaAthleteSummary, BetaIntelligenceReadModel } from "./contracts";

const baseActivity = {
  filmRoomOpens: 0,
  photosOpens: 0,
  mediaViews: 0,
  profileEdits: 0,
  careerCorrections: 0,
  mediaUploads: 0,
  shares: 0,
  socialLinkClicks: 0,
  returned: false,
  lastActivityAt: null,
};

const athletes: BetaAthleteSummary[] = [
  {
    id: "fixture-athlete-01",
    name: "Beta Athlete 01",
    cohort: "Cal alumni",
    status: "active",
    invitedAt: "2026-08-02T17:00:00.000Z",
    joinedAt: "2026-08-03T16:20:00.000Z",
    lockerViewedAt: "2026-08-03T16:24:00.000Z",
    lockerClaimedAt: "2026-08-03T16:28:00.000Z",
    lockerEditedAt: "2026-08-04T18:12:00.000Z",
    lockerSharedAt: "2026-08-05T20:05:00.000Z",
    activity: { ...baseActivity, lockerViews: 9, filmRoomOpens: 4, photosOpens: 3, mediaViews: 7, profileEdits: 3, careerCorrections: 1, mediaUploads: 2, shares: 2, socialLinkClicks: 3, returned: true, lastActivityAt: "2026-08-14T18:24:00.000Z" },
    feedback: { completedAt: "2026-08-06T18:00:00.000Z", lockerValueRating: 5, careerAccuracyRating: 3, mediaValueRating: 5, wouldShare: true, willingnessToPay: true, paymentExpectation: "$10–20 monthly if updates stay current", digitalIntelligenceInterest: true, analyticsInterest: true, organizationInterest: true, biggestProblem: "My college media is scattered across old pages.", favoriteFeature: "Seeing career media in one place.", missingFeature: "A way to find broken or outdated profiles." },
    insights: [
      { id: "insight-01", category: "missing_career_media", description: "Two seasons have no linked game media.", severity: "high", status: "open" },
      { id: "insight-02", category: "incorrect_career_information", description: "One roster page lists an outdated position.", severity: "medium", status: "monitoring" },
    ],
    caseStudyCandidate: true,
    caseStudyPermission: "pending",
    baselineCapturedAt: "2026-08-04T19:00:00.000Z",
    engagementLevel: "high",
  },
  {
    id: "fixture-athlete-02",
    name: "Beta Athlete 02",
    cohort: "former NFL",
    status: "active",
    invitedAt: "2026-08-05T17:00:00.000Z",
    joinedAt: "2026-08-06T17:10:00.000Z",
    lockerViewedAt: "2026-08-06T17:14:00.000Z",
    lockerClaimedAt: "2026-08-06T17:20:00.000Z",
    lockerEditedAt: "2026-08-07T20:00:00.000Z",
    lockerSharedAt: null,
    activity: { ...baseActivity, lockerViews: 5, filmRoomOpens: 2, photosOpens: 1, mediaViews: 4, profileEdits: 1, careerCorrections: 2, returned: true, lastActivityAt: "2026-08-13T15:40:00.000Z" },
    feedback: { completedAt: "2026-08-08T18:00:00.000Z", lockerValueRating: 4, careerAccuracyRating: 2, mediaValueRating: 4, wouldShare: true, willingnessToPay: null, paymentExpectation: "Would expect my former team to provide it", digitalIntelligenceInterest: true, analyticsInterest: false, organizationInterest: true, biggestProblem: "Awards and transaction history are incomplete online.", favoriteFeature: "Career timeline.", missingFeature: "Verified source labels." },
    insights: [
      { id: "insight-03", category: "missing_awards", description: "Conference award is absent from two major profiles.", severity: "high", status: "open" },
      { id: "insight-04", category: "legacy_gaps", description: "Professional transaction history stops after rookie season.", severity: "critical", status: "open" },
    ],
    caseStudyCandidate: true,
    caseStudyPermission: "not_requested",
    baselineCapturedAt: null,
    engagementLevel: "high",
  },
  {
    id: "fixture-athlete-03",
    name: "Beta Athlete 03",
    cohort: "current college",
    status: "active",
    invitedAt: "2026-08-08T17:00:00.000Z",
    joinedAt: "2026-08-09T19:05:00.000Z",
    lockerViewedAt: "2026-08-09T19:09:00.000Z",
    lockerClaimedAt: "2026-08-09T19:16:00.000Z",
    lockerEditedAt: null,
    lockerSharedAt: null,
    activity: { ...baseActivity, lockerViews: 3, filmRoomOpens: 1, photosOpens: 2, mediaViews: 2, returned: false, lastActivityAt: "2026-08-09T19:18:00.000Z" },
    feedback: null,
    insights: [{ id: "insight-05", category: "social_identity_issues", description: "Two social profiles use inconsistent names and imagery.", severity: "medium", status: "open" }],
    caseStudyCandidate: false,
    caseStudyPermission: "not_requested",
    baselineCapturedAt: null,
    engagementLevel: "medium",
  },
  {
    id: "fixture-athlete-04",
    name: "Beta Athlete 04",
    cohort: "organic",
    status: "invited",
    invitedAt: "2026-08-12T17:00:00.000Z",
    joinedAt: null,
    lockerViewedAt: null,
    lockerClaimedAt: null,
    lockerEditedAt: null,
    lockerSharedAt: null,
    activity: { ...baseActivity, lockerViews: 0 },
    feedback: null,
    insights: [],
    caseStudyCandidate: false,
    caseStudyPermission: "not_requested",
    baselineCapturedAt: null,
    engagementLevel: "low",
  },
  {
    id: "fixture-athlete-05",
    name: "Beta Athlete 05",
    cohort: "high visibility",
    status: "completed",
    invitedAt: "2026-07-25T17:00:00.000Z",
    joinedAt: "2026-07-26T16:00:00.000Z",
    lockerViewedAt: "2026-07-26T16:02:00.000Z",
    lockerClaimedAt: "2026-07-26T16:08:00.000Z",
    lockerEditedAt: "2026-07-27T17:00:00.000Z",
    lockerSharedAt: "2026-07-28T17:00:00.000Z",
    activity: { ...baseActivity, lockerViews: 14, filmRoomOpens: 6, photosOpens: 5, mediaViews: 12, profileEdits: 4, mediaUploads: 3, shares: 5, socialLinkClicks: 8, returned: true, lastActivityAt: "2026-08-11T17:00:00.000Z" },
    feedback: { completedAt: "2026-07-29T17:00:00.000Z", lockerValueRating: 5, careerAccuracyRating: 4, mediaValueRating: 5, wouldShare: true, willingnessToPay: true, paymentExpectation: "Annual plan with a managed archive", digitalIntelligenceInterest: true, analyticsInterest: true, organizationInterest: false, biggestProblem: "Search results do not reflect my full career.", favoriteFeature: "Film Room.", missingFeature: "Search visibility tracking." },
    insights: [
      { id: "insight-06", category: "search_discoverability", description: "Official Locker is not yet present in top search results.", severity: "high", status: "monitoring" },
      { id: "insight-07", category: "outdated_athlete_profiles", description: "A prominent profile still lists the prior team.", severity: "medium", status: "resolved" },
    ],
    caseStudyCandidate: true,
    caseStudyPermission: "granted",
    baselineCapturedAt: "2026-07-26T20:00:00.000Z",
    engagementLevel: "high",
  },
];

export const betaIntelligenceFixture: BetaIntelligenceReadModel = {
  source: "fixture",
  generatedAt: "2026-08-16T19:00:00.000Z",
  athletes,
};
