import Link from "next/link";
import { COOLDOWN_WORK, FINDINGS, RESEARCH_ATHLETE, TRIAL_PLAN, type FindingState, type ResearchViewData } from "@/lib/intelligence/research";
import styles from "./intelligence.module.css";

const stateLabels: Record<FindingState, string> = { observed: "Observed", documented: "Documented only", blocked: "Last test blocked", not_implemented: "Integration gap" };
function pacific(instant: string) { return new Intl.DateTimeFormat("en-US", { timeZone: "America/Los_Angeles", month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZoneName: "short" }).format(new Date(instant)); }

export function ResearchView({ data }: { data: ResearchViewData }) {
  const { cooldown, trial } = data;
  return <div className={styles.research}>
    <section className={styles.overview} aria-label="Research status">
      <div><span className={styles.eyebrow}>Sportradar discovery / NFL trial</span><h2>Career facts connected.<br />Evidence ready to inspect.</h2><p className={styles.lead}>Reviewed USC and NFL game evidence now connects Keith Rivers to dated Moments and supporting performances. A real anniversary demonstrates the path from Moment to Signal to Opportunity.</p><div className={styles.linkRow}><Link className={styles.primaryLink} href={`/admin/intelligence?view=athlete&athlete=${RESEARCH_ATHLETE.id}&q=Keith+Rivers`}>Inspect Keith Rivers ↗</Link><Link className={styles.textLink} href="/admin/intelligence?view=example">See the intelligence display ↗</Link></div></div>
      <aside className={styles.trialWindow} aria-label="Sportradar trial window"><span className={styles.eyebrow}>Trial research window</span><div className={styles.dayCount}>{trial.daysRemaining}<span>days left</span></div><p>Research deadline <strong>October 10, 2026</strong></p><p className={styles.note}>Deadline corrected by the founder on September 30. The provider&apos;s exact expiration time is not yet recorded.</p></aside>
    </section>
    <section className={styles.cooldown} aria-label="Provider cooldown"><span className={styles.statusDot} aria-hidden="true" /><div><strong>{cooldown.state === "active" ? "Provider calls paused" : cooldown.state === "elapsed" ? "Shared cooldown has elapsed" : cooldown.state === "clear" ? "No rate-limit entry found" : "Cooldown status unavailable"}</strong><p>{cooldown.state === "active" && cooldown.until ? `Shared ledger cooldown until ${pacific(cooldown.until)}. Work on stored evidence and review contracts in the meantime.` : cooldown.state === "elapsed" ? "An earlier request returned HTTP 429. A later paced probe succeeded; elapsed cooldown does not guarantee access for the next reserved call." : cooldown.state === "clear" ? "This is the request-ledger state, not a guarantee of provider quota or access." : "We could not read the request ledger. Do not assume provider calls are permitted."}</p></div><span className={styles.ledgerLabel}>Ledger checked {pacific(data.checkedAt)}</span></section>
    <div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Captured September 30, 2026</span><h2>Findings so far</h2></div><p>Observed results and untested capabilities are kept separate.</p></div>
    <dl className={styles.snapshot} aria-label="Dated research snapshot"><div><dt>Canonical Career IDs</dt><dd>296</dd></div><div><dt>Reviewed provider mappings</dt><dd>1</dd></div><div><dt>Imported profile snapshots</dt><dd>2</dd></div><div><dt>Catalog years listed</dt><dd>2000–2026</dd></div></dl>
    <section className={styles.findings} aria-label="Provider findings and evidence"><div className={styles.findingHeader} aria-hidden="true"><span>Research area</span><span>Finding & evidence</span><span>Next proof</span></div>{FINDINGS.map(finding => <article key={finding.id} className={styles.finding}><div><h3>{finding.title}</h3><span className={`${styles.findingState} ${finding.state === "observed" ? styles.observed : finding.state === "blocked" ? styles.blocked : ""}`}>{stateLabels[finding.state]}</span></div><div><p>{finding.detail}</p><p className={styles.evidenceLabel}>{finding.evidence}</p>{finding.href && <a href={finding.href} target="_blank" rel="noopener noreferrer" className={styles.textLink}>Open evidence ↗</a>}</div><p className={styles.nextProof}>{finding.next}</p></article>)}</section>
    <div className={styles.workGrid}><section className={styles.workPanel} aria-label="Work during cooldown"><span className={styles.eyebrow}>Independent of provider access</span><h2>Work during cooldown</h2><ol className={styles.workList}>{COOLDOWN_WORK.map((item, index) => <li key={item.title}><span className={styles.workNumber}>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.detail}</p><span className={styles.evidenceLabel}>{item.state}</span></div></li>)}</ol><p className={styles.note}>Opening this view reads the existing request ledger. It makes no Sportradar requests and creates no athlete or cohort records.</p></section><section className={styles.workPanel} aria-label="Discovery plan through October 10"><span className={styles.eyebrow}>September 30 → October 10</span><h2>Complete discovery by October 10</h2><ol className={styles.planList}>{TRIAL_PLAN.map(item => <li key={item.window}><span className={styles.planWindow}>{item.window}</span><h3>{item.title}</h3><p>{item.detail}</p></li>)}</ol></section></div>
    <footer className={styles.researchFooter}>Evidence: reviewed mapping/profile snapshots, the September 30 research probe, and the repository source audit. Snapshot counts are dated observations, not live inventory or pilot success metrics.</footer>
  </div>;
}
