-- Preview lockers: standalone, demo-only athlete lockers generated by the
-- internal scraper tool (admin enters a name, the onboarding pipeline scrapes
-- facts/photos, admin adds video links manually). Intentionally isolated in
-- its own table — never joined against `players` — so demo data can never
-- leak into, or be broken by changes to, the real athlete locker pipeline.
--
-- Read is public (a preview link is meant to be shared with a prospect during
-- a demo, same as a real locker page). Write is restricted to internal
-- platform admins via the existing `public.is_internal_admin()` predicate.

create table if not exists public.preview_lockers (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  full_name text not null,
  position text,
  level text check (level in ('hs', 'college', 'pro', 'former')),
  school text,
  hometown text,
  jersey text,
  height_in smallint,
  weight_lbs smallint,
  dob date,
  games_played integer,
  headshot_url text,
  hero_video_url text,
  bio text not null default '',
  athlete_quote text,
  athlete_quote_author text,
  -- Display-only jsonb blobs mirroring the shapes LockerView/PhotoRoomView
  -- already consume (see lib/preview-lockers/mapper.ts) — kept schemaless
  -- here since this table only ever backs a read-only demo page.
  school_info jsonb not null default '{}'::jsonb,
  nfl_info jsonb not null default '{}'::jsonb,
  schools jsonb not null default '[]'::jsonb,
  pro_teams jsonb not null default '[]'::jsonb,
  awards jsonb not null default '[]'::jsonb,
  career_stats jsonb not null default '[]'::jsonb,
  career_seasons jsonb not null default '[]'::jsonb,
  videos jsonb not null default '[]'::jsonb,
  photos jsonb not null default '[]'::jsonb,
  -- Raw scraper draft + provenance, kept for debugging a bad scrape.
  source jsonb not null default '{}'::jsonb,
  pipeline_run_id uuid references public.onboarding_pipeline_runs(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.preview_lockers is
  'Demo-only athlete lockers generated by the admin preview-generator tool. Fully isolated from public.players — never joined against it.';

drop trigger if exists preview_lockers_set_updated_at on public.preview_lockers;
create trigger preview_lockers_set_updated_at
  before update on public.preview_lockers
  for each row execute function public.set_updated_at();

alter table public.preview_lockers enable row level security;

revoke all on table public.preview_lockers from public, anon, authenticated;
grant select on table public.preview_lockers to anon, authenticated;
grant insert, update, delete on table public.preview_lockers to authenticated;

drop policy if exists "Anyone can view preview lockers" on public.preview_lockers;
create policy "Anyone can view preview lockers"
  on public.preview_lockers for select
  to anon, authenticated
  using (true);

drop policy if exists "Internal admins manage preview lockers" on public.preview_lockers;
create policy "Internal admins manage preview lockers"
  on public.preview_lockers for all
  to authenticated
  using ((select public.is_internal_admin()))
  with check ((select public.is_internal_admin()));
