/* Read-only, reviewed BLTZ snapshot. No provider requests or inferred relationships. */
window.BLTZ_DATA = {
  asOf:'2026-10-01', fetchedAt:'2026-10-01T03:55:39Z',
  athlete:{id:'c5dae871-a277-4256-9a0c-17a40940ad3f',name:'Keith Rivers',position:'Outside linebacker',sport:'Football',school:'USC',profileTeamLabel:'BUF',status:'Former athlete',identityVerified:false,lastRegularSeason:2014,retirementDate:'2015-07-30',careerRelationships:[],achievements:[],media:[],externalIdentity:{provider:'Sportradar',sport:'Football',league:'NFL',id:'d2c5d2fa-dd75-444e-b8e0-63c31a3791be',method:'Manual review',verifiedAt:'2026-09-18T20:28:13Z',confidence:null}},
  moments:{
    usc:{key:'usc',id:'24395222-ee28-4a8b-9c1e-e5f06e0dd705',title:'USC vs. Washington',canonicalTitle:'Keith Rivers participates in USC vs. Washington',date:'2006-10-07',dateLabel:'October 7, 2006',season:'2006',team:'USC',opponent:'Washington',competition:'College football',relationship:'Participant',confidence:99,stats:[{value:12,label:'Tackles'},{value:1,label:'Tackle for loss'},{value:2,label:'Deflections'}],summary:'Keith Rivers recorded 12 tackles, one tackle for loss and two deflections against Washington.',why:'The 20-year anniversary falls on October 7, 2026 — six days after this review date. Two official USC sources establish participation, date and performance.',signal:{type:'Historical anniversary',score:92,confidence:99,anniversaryYears:20,target:'2026-10-07',daysAway:6,reason:'40 base + 32 date proximity + 20 five-year anniversary bonus = 92/100.'},opportunity:{type:'Alumni retrospective',status:'Human review',summary:'Review a USC alumni retrospective around the anniversary.',missing:['Verified moment-to-media links','Usage clearance','Athlete preferences']},sourceKeys:['uscPostgame','uscBio'],sourceCount:2,media:[],clearedMedia:[],evidenceCount:2},
    nfl:{key:'nfl',id:'dbef2bf5-eea9-4920-94dc-18851eec4254',title:'Buffalo Bills at Chicago Bears',canonicalTitle:'Keith Rivers participates in Buffalo Bills at Chicago Bears',date:'2014-09-07',dateLabel:'September 7, 2014',season:'2014',team:'Buffalo Bills',opponent:'Chicago Bears',competition:'NFL regular season',relationship:'Participant',confidence:99,stats:[{value:3,label:'Tackles'},{value:1,label:'Assist'},{value:4,label:'Combined tackles'}],score:'Bills 23 · Bears 20',plays:9,summary:'The game statistics record three tackles and one assist for Keith Rivers. Play-by-play confirms participation in nine distinct defensive plays.',why:'This is a sourced career event. The reviewed data does not establish a record, performance spike or milestone.',signal:null,opportunity:null,sourceKeys:['nflStats','nflPbp'],sourceCount:2,media:[],clearedMedia:[],evidenceCount:null}
  },
  sources:{
    uscPostgame:{name:'USC Athletics',title:'USC vs. Washington Quotes — 10-7-2006',kind:'Postgame article',url:'https://usctrojans.com/news/2006/10/7/USC_vs_Washington_Quotes_10_7_2006',published:'2006-10-07',fetchedAt:'2026-10-01T03:55:39Z',confidence:99,assertion:'USC’s official postgame article establishes Keith Rivers’ participation and the October 7, 2006 game date.',rights:'Unknown',evidenceId:'48e724e5-d1c3-46fd-ad8f-1f2016c850d3'},
    uscBio:{name:'USC Athletics',title:'2007 USC Senior Football Player Biographies',kind:'Official biography · PDF',url:'https://usctrojans.com/documents/download/2015/4/30/07seniorbiosfb-final.pdf',published:null,fetchedAt:'2026-10-01T03:55:39Z',confidence:99,assertion:'The Washington game entry credits Keith Rivers with 12 tackles, one tackle for loss and two deflections.',dateNote:'2007 biography. The 2015 upload path does not establish its original publication date.',rights:'Unknown',evidenceId:'0063fd2c-2110-49b3-b638-f788a735b776'},
    nflStats:{name:'Sportradar NFL',title:'Bills–Bears game statistics',kind:'Game statistics',url:null,locator:'/nfl/official/trial/v7/en/games/eb3bb333-6ae5-417c-b9e3-1d3dfdb8673e/statistics.json',published:null,eventDate:'2014-09-07',fetchedAt:'2026-10-01T03:56:14.559Z',confidence:99,assertion:'The exact Keith Rivers player row records three tackles, one assist and four combined tackles. Buffalo won 23–20.',rights:'Unknown',evidenceId:'271c5e64-ccd8-4ed5-bf90-7d15d123c738'},
    nflPbp:{name:'Sportradar NFL',title:'Bills–Bears play-by-play',kind:'Participation evidence',url:null,locator:'/nfl/official/trial/v7/en/games/eb3bb333-6ae5-417c-b9e3-1d3dfdb8673e/pbp.json',published:null,eventDate:'2014-09-07',fetchedAt:'2026-10-01T03:56:17.976Z',confidence:99,assertion:'Nine distinct source-confirmed defensive plays establish participation only; no milestone or unusual performance is inferred.',rights:'Unknown'}
  },
  content:[
    {title:'How Keith Rivers Went from NFL Linebacker to Blue-Chip Art Aficionado',publisher:'1stDibs Introspective',url:'https://www.1stdibs.com/introspective-magazine/keith-rivers/',kind:'Interview',era:'Post-career',published:'2021-11-07',videoRelease:null,confidence:99,summary:'An interview about art collecting connects Keith Rivers to the Bengals, Bills and Giants.',rights:'Unknown'},
    {title:'NO RESERVE from The Baer Faxt — Issue #1',publisher:'The Baer Faxt',url:'https://noreserve.thebaerfaxt.com/p/no-reserve-from-the-baer-faxt-issue-1-f85b',kind:'Interview newsletter',era:'Post-career',published:'2025-09-08',videoRelease:null,confidence:98,summary:'The publisher identifies Keith Rivers and links a full interview and a clip. Newsletter date does not establish video upload date.',rights:'Unknown'},
    {title:'Keith Rivers interview clip',publisher:'The Baer Faxt',url:'https://www.youtube.com/watch?v=4ziGmXHt_g8',kind:'Video',era:'Post-career',published:null,videoRelease:null,confidence:98,summary:'Subject confirmed by publisher. Upload date is unknown; this is athlete context with no established link to either game.',rights:'Unknown'},
    {title:'Keith Rivers full interview',publisher:'The Baer Faxt',url:'https://www.youtube.com/watch?v=_kVz5UI_tJE',kind:'Video',era:'Post-career',published:null,videoRelease:null,confidence:98,summary:'Subject confirmed by publisher. Upload date and usage clearance are unknown.',rights:'Unknown'},
    {title:'Keith Rivers retires',publisher:'Dallas Cowboys',url:'https://www.dallascowboys.com/news/r-mcclain-mcfadden-placed-on-pup-list-to-start-camp-keith-rivers-retires-380591',kind:'Article',era:'Post-career',published:'2015-07-30',eventDate:'2015-07-30',confidence:99,summary:'Dallas reported moving Rivers to the reserve/retired list on July 30, 2015. His final regular NFL season was 2014.',rights:'Unknown'},
    {title:'Under Review with Keith Rivers',publisher:'Buffalo Bills',url:'https://www.buffalobills.com/video/under-review-with-keith-rivers-12925098',kind:'Video',era:'Career-era context',published:null,videoRelease:null,confidence:99,summary:'Buffalo’s official interview connects Rivers to USC and art interests. An exact release date is not supplied.',rights:'Unknown'}
  ],
  limits:{career:'No normalized roster or career relationships are recorded. Source references are context, not verified season-by-season affiliations.',media:'No media assets are linked to either moment. Article and video references do not establish usage clearance.',achievements:'No reviewed award or achievement is supplied in this snapshot.',relationships:'No reviewed teammate or contributor relationship is supplied.',scores:'Scores measure editorial review priority, not probability, earnings or monetary value.',signals:'Signals and opportunities are computed for human review; they are not persisted actions.'}
};
